Add Verified to PackageMetadata, currently only used by NuGet.
microsoft/OSSGadget pull request #359
Opened 2022-10-21 18:58 UTC by jpinz

It states if the specified package is verified as a part of the prefix/scope/namespace it is in.
https://learn.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation
Some packages in a NuGet prefix could not be a part of the prefix itself. So this adds the ability to assert that it is verified to be a part of the namespace.

For example: 
This package [`Microsoft.CST.OSSGadget.Shared`](https://www.nuget.org/packages/Microsoft.CST.OSSGadget.Shared/) is verified to be a part of the `Microsoft.` prefix (Look under the name for the checkmark)
But, the package [`Microsoft.Office.Core.Excel`](https://www.nuget.org/packages/Microsoft.Office.Core.Excel/) is not verified as a part of the `Microsoft.` prefix. Same for [`Microsoft.Azure.Functions.Library`](https://www.nuget.org/packages/Microsoft.Azure.Functions.Library/) and plenty of others.

2022-10-21 19:09 UTC, pmalmsten approved these changes

2022-10-21 19:09 UTC, scovetta commented
Suggestion -- instead of "verified", maybe something like "isReservedNamespace" or something more specific? Also, if *only* NuGet has it (or exposes it), I'm not sure it should be part of the base model.

I guess `null` would mean "no information available"?

2022-10-21 19:12 UTC, scovetta submitted a review, later dismissed
See my other comment -- I think Verified is the wrong word here -- probably not PrefixReserved either, since that's an implementation detail -- maybe NamespaceReserved or something like that?

Also, if only NuGet implements/exposes this, should it be in the base model or just the NuGetPackageManager? Are there other fields that we have only in the child models?

2022-10-21 19:13 UTC, gfs requested changes

2022-10-21 19:13 UTC, gfs commented on src/Shared/Model/Metadata/NuGetPackageVersionMetadata.cs
> +    public bool Verified { get; init; }
I don't think this is a good name for this field. Verified on its own to me would indicate that we have done some verification of the package. Prefix reserved seems to be much more accurately describing the state.

2022-10-21 19:13 UTC, gfs commented on src/Shared/Model/PackageMetadata.cs
> +        [JsonProperty(PropertyName = "verified", NullValueHandling = NullValueHandling.Ignore)]
Json property name differs from NugetPackageVersionMetadata. Same concern that I don't believe this is the right terminology.

2022-10-21 20:50 UTC, jpinz commented
@gfs @scovetta I reverted the changes for the NuGet metadata related tweaks I made. And instead implemented a method on the NuGetProjectManager that just returns a boolean whether or not the package is verified to be a part of a reserved prefix.

2022-10-21 22:29 UTC, gfs commented
Can you add a test case or two for this new functionality?

2022-10-24 15:04 UTC, jpinz commented
> Can you add a test case or two for this new functionality?

@gfs done

2022-10-24 21:30 UTC, gfs reviewed
Minor nits on the names for things added to the interface.

2022-10-24 21:30 UTC, gfs commented on src/Shared/Contracts/IManagerPackageActions.cs
> +    Task<bool> GetReservedNamespaceAsync(PackageURL packageUrl, bool useCache = true, CancellationToken cancellationToken = default);
Can we rename this to something like "GetHasReservedNamespaceAsync"? This returns bool but based on the method name I'd assume it returns the namespace itself.

2022-10-24 21:30 UTC, gfs commented on src/Shared/PackageActions/NuGetPackageActions.cs
> +    public async Task<bool> GetReservedNamespaceAsync(PackageURL packageUrl, bool useCache = true, CancellationToken cancellationToken = default)
Same comment as above with name of method vs return type

2022-10-24 21:30 UTC, gfs commented on src/Shared/PackageManagers/NuGetProjectManager.cs
> +        public async Task<bool> GetPackagePrefixReservedAsync(PackageURL purl, bool useCache = true)
same comment where the method name makes me expect a string or some meaningful value but this returns a bool.

2022-10-24 22:00 UTC, gfs approved these changes

2022-10-24 23:17 UTC, merged